export const SUPPORTED_LANGUAGES = [
  { label: "SELECT A LANGUAGE",extension: "",  value: "SELECT A LANGUAGE" },
  { label: "JavaScript",extension: ".js",  value: "javascript" },
  { label: "TypeScript",extension: ".ts", value: "typescript" },
  { label: "HTML",extension: ".html", value: "html" },
  { label: "CSS", extension: ".css",value: "css" },
  { label: "SQL", extension: ".sql",value: "sql" },
  { label: "React JSX",extension: ".jsx", value: "jsx" },
  { label: "React TSX",extension: ".tsx", value: "tsx" },
  { label: "Python",extension: ".py", value: "python" },
  { label: "Java", extension: ".java", value: "java" },
  { label: "C#", extension: ".cs", value: "csharp" },
  { label: "C++", extension: ".cpp", value: "cpp" },
  { label: "PHP", extension: ".php", value: "php" },
  { label: "Go", extension: ".go", value: "go" },
  { label: "Rust", extension: ".rs", value: "rust" },
  { label: "Swift", extension: ".swift", value: "swift" },
  { label: "Kotlin", extension: ".kt", value: "kotlin" },
  { label: "Ruby", extension: ".rb", value: "ruby" },
  { label: "Dart", extension: ".dart", value: "dart" },
  { label: "C", extension: ".c", value: "c" },
  { label: "JSON", extension: ".json", value: "json" },
  { label: "Markdown", extension: ".md", value: "markdown" },
  { label: "YAML", extension: ".yaml", value: "yaml" },
];